export const productSeed = [
  { name: 'pencil', description: 'pencil blue', price: '1.20', amount: 40 },
  { name: 'notebook', description: 'large notebook', price: '5.50', amount: 30 },
  { name: 'pen', description: 'black pen', price: '0.80', amount: 50 },
  { name: 'eraser', description: 'small eraser', price: '0.50', amount: 60 },
  { name: 'ruler', description: '30cm ruler', price: '1.50', amount: 20 },
  { name: 'highlighter', description: 'yellow highlighter', price: '1.00', amount: 35 },
  { name: 'sticky notes', description: 'pack of sticky notes', price: '2.00', amount: 25 },
  { name: 'scissors', description: 'sharp scissors', price: '3.50', amount: 15 },
  { name: 'marker', description: 'permanent marker', price: '2.50', amount: 20 },
  { name: 'calculator', description: 'basic calculator', price: '8.00', amount: 10 },
  { name: 'folder', description: 'plastic folder', price: '1.80', amount: 30 },
  { name: 'glue stick', description: 'large glue stick', price: '2.20', amount: 25 },
  { name: 'paper clips', description: 'pack of paper clips', price: '0.75', amount: 50 },
  { name: 'note pad', description: 'small note pad', price: '1.25', amount: 40 },
  { name: 'tape dispenser', description: 'tape dispenser with tape', price: '3.00', amount: 20 },
  { name: 'index cards', description: 'pack of index cards', price: '1.50', amount: 30 },
  { name: 'rubber bands', description: 'bag of rubber bands', price: '0.50', amount: 100 },
  { name: 'folders', description: 'pack of folders', price: '5.00', amount: 10 },
  { name: 'sharpener', description: 'pencil sharpener', price: '1.00', amount: 30 },
  { name: 'stapler', description: 'standard stapler', price: '4.50', amount: 15 },
  { name: 'notebook paper', description: 'pack of notebook paper', price: '3.50', amount: 20 },
  { name: 'binder', description: '3-ring binder', price: '4.00', amount: 15 },
  { name: 'markers', description: 'pack of markers', price: '6.00', amount: 20 },
  { name: 'desk organizer', description: 'desktop organizer', price: '7.50', amount: 10 },
  { name: 'whiteboard', description: 'small whiteboard', price: '12.00', amount: 5 },
  { name: 'highlighters', description: 'pack of highlighters', price: '4.50', amount: 15 },
  { name: 'notebook binder', description: 'binder for notebooks', price: '3.00', amount: 25 },
  { name: 'chalk', description: 'box of chalk', price: '1.50', amount: 30 },
  { name: 'staples', description: 'box of staples', price: '2.00', amount: 40 },
  { name: 'file folders', description: 'pack of file folders', price: '5.50', amount: 10 },
  { name: 'push pins', description: 'box of push pins', price: '0.75', amount: 50 },
  { name: 'notebook dividers', description: 'set of notebook dividers', price: '2.50', amount: 20 },
  { name: 'highlighter pens', description: 'set of highlighter pens', price: '6.00', amount: 15 },
  { name: 'clipboard', description: 'standard clipboard', price: '3.00', amount: 20 },
  { name: 'envelopes', description: 'pack of envelopes', price: '4.00', amount: 25 },
  { name: 'tape', description: 'roll of tape', price: '1.50', amount: 40 },
  { name: 'composition notebook', description: 'composition notebook', price: '2.00', amount: 30 },
  { name: 'rubber stamps', description: 'set of rubber stamps', price: '8.00', amount: 10 },
  { name: 'printer paper', description: 'pack of printer paper', price: '6.50', amount: 15 },
  { name: 'printer ink', description: 'printer ink cartridge', price: '20.00', amount: 5 },
  { name: 'sticky tack', description: 'pack of sticky tack', price: '1.00', amount: 50 },
];

export const userSeed = [
  {
    email: 'admin@mail.com',
    password: 'fed42fb0fabde4000af60bf1f63037905176d6db1df5c2ee6214ee83565de36b',
    role: 'admin',
  },
  {
    email: 'requester@mail.com',
    password: 'fed42fb0fabde4000af60bf1f63037905176d6db1df5c2ee6214ee83565de36b',
    role: 'requester',
  },
  {
    email: 'manager@mail.com',
    password: 'fed42fb0fabde4000af60bf1f63037905176d6db1df5c2ee6214ee83565de36b',
    role: 'manager',
  },
];
