version: '3.8'

services:
  mariadb:
    image: mariadb
    container_name: mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wonders
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - ./src/tests/config/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
      - mariadb_data:/var/lib/mysql
    ports:
      - '3306:3306'

volumes:
  mariadb_data:
    driver: local
